### ISSUE TITLE
Not very random

### ISSUE THREAD

**Issue by CrazySpence** [spiroharvey/c64#2]
Love this, especially with NYT buying the popular one

Anyways kept getting dwell and other words in the same order so i added
5 r=rnd(-ti) 
to the beginning of the code and it seems to be way better at random now

if that was in the game loop it could re init the random seed every game 

Anyways just an idea

**Comment by spiroharvey** [comment]
Sorry I only just saw this now by seeing my "Issues" tab had a number on it! 
Thank you. That's a great idea and reminds me I need to add and upload the features I promised for the next version.

**Comment by spiroharvey** [comment]
Yay! I can close an issue!
haha Thanks Spence. :)
