### ISSUE TITLE
Not all data is provided ...

### ISSUE THREAD

**Issue by BacchusFLT** [spiroharvey/c64#3]
If one would like to assemble the projects under Asm, then not all the data is there to do it. If you feel it's not yours to publish, then please at least provide pointers to the relevant source.

**Comment by spiroharvey** [comment]
The macro.asm is in the repo, but you have to adjust the path in the source. I just uploaded them into the same folder here, but they are in different folders on my computer.
The font I used is linked in the source, and I figured the SID and KOALA image can be replaced with anything you choose. Are they the files you would like me to upload or link to?

**Comment by spiroharvey** [comment]
Updated the repo and have added in all the files and given credit with links to where they were sourced.
All code now assembles right out of that folder, so please reclone and try again. :)

**Comment by BacchusFLT** [comment]
Great - I will have look when I have the time, but I'm sure it's great.

Den tors 19 jan. 2023 20:06Spiro Harvey ***@***.***> skrev:
